### ISSUE TITLE
Problem with decoding extrinsics

### ISSUE THREAD

**Issue by MarcSky** [subscan-explorer/subscan-essentials#167]
Hello.
I try to sync polkadot blockchain with subscan, but I stuck with block 2898661.
I got error 
```
ERR: Decode Extrinsic get error  Recovering from panic in DecodeExtrinsic error is: Not find Extrinsic Lookup 1400, please check metadata info
ERR: Decode Extrinsic get error  Recovering from panic in DecodeExtrinsic error is: Not find Extrinsic Lookup 0a00, please check metadata info

```

I going to redis metadata key and see that

```
get polkadot:metadata
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

I get subscan from master version. Can someone to help me please :)

**Comment by freehere107** [comment]
@MarcSky https://polkadot.subscan.io/block/2898661. It seems useless to contain special extrinsics
