### ISSUE TITLE
Moonbeam: Subscan does not show a complete list of transactions.

### ISSUE THREAD

**Issue by will-yijinin** [subscan-explorer/subscan-essentials#181]
https://moonbeam.subscan.io/account/0x604efcc46578c43adc9519d5f14a2a963cd5b81b

https://moonbeam.moonscan.io/address/0x604efcc46578c43adc9519d5f14a2a963cd5b81b

For the same address, subscan only shows balances.transferKeepAlive transactions, moonscan only shows ethereum.transact transactions. This seems a severe UX bug to me.

**Comment by freehere107** [comment]
@will-yijinin This issue is currently being developed in the plan, thank you for your feedback

**Comment by freehere107** [comment]
@will-yijinin https://moonbeam.subscan.io/account/0x604efcc46578c43adc9519d5f14a2a963cd5b81b?tab=transaction
This has been supported
