### ISSUE TITLE
Acala: Support display RMRK token

### ISSUE THREAD

**Issue by zqhxuyuan** [subscan-explorer/subscan-essentials#182]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/1088525/156485897-d846100b-a0e6-44cc-a501-12eec8e0021d.png">

i.e [this account](https://karura.subscan.io/account/pBHsSJZL26jaQjkHHpSWgiB3z432XFw1rAaaqNc8TyZS6ZJ) has RMRK by query tokens on karura:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1088525/156485998-1c3691ae-8072-44b6-8f3a-952c3d41b2f9.png">

different parachain may use different way to represent statemine asset. i.e. Acala use foreign asset, but we also provide asset-registry query method:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1088525/156486266-3211ace1-c26d-4d77-9e6d-65ebdf073426.png">

**Comment by freehere107** [comment]
@zqhxuyuan This feature has been updated
