### ISSUE TITLE
writing custom plugins to  indexed more data 

### ISSUE THREAD

**Issue by andropixels** [subscan-explorer/subscan-essentials#185]
Can we save accounts , transfers to the database with plugins ?
if yes how should i approach to write a plugin for saving accounts and transfers from the substrate chain  to database ?

**Comment by freehere107** [comment]
@andropixels Yes, https://github.com/subscan-explorer/subscan-essentials/tree/master/plugins/balance is a demo to save account

**Comment by andropixels** [comment]
@freehere107 thanks for the reply,
Yes I checked that demo, but it returns null data. 
The request I made for accounts:
curl -X POST 'http://127.0.0.1:4399/api/plugin/balance/accounts' -- header Content-Type: application/json"
--data-raw '{
"row": 10, "page": 1
}
 
The responce I got back and it is giving me null list 
{"code":0,"message":"success","ttl":1,"data": {"count":0,"list":[]}]

Why is that do I have to make any changes? 
Please suggest.
