### ISSUE TITLE
Centrifuge.subscan stopped working

### ISSUE THREAD

**Issue by ImdioR** [subscan-explorer/subscan-essentials#195]
Good day dear Subscan Team
I`m an Ambassador of Centrifuge and we noticed that https://centrifuge.subscan.io/ has stopped to work.
Can you kindly please take a look at what is happened?
![image](https://user-images.githubusercontent.com/90972248/172466882-e74ccea4-68c6-4f9e-8c96-ecada485a2c1.png)

Issue: Can not track any history or wallet address balance.
Thank you in advance. 
Best Regards.

**Comment by wi1dcard** [comment]
Hi @ImdioR! Thank you for reporting this issue. This was caused by an incorrect internal config and it has been fixed. Let us know if there's anything we can help with!
