### ISSUE TITLE
Incorrect information displayed

### ISSUE THREAD

**Issue by ImdioR** [subscan-explorer/subscan-essentials#197]
Good day, Subscan Team.
I would like to report an issue with Interlay, Zeitgeist balance displaying on sub.id website.
![gitsubid](https://user-images.githubusercontent.com/90972248/178141804-4ca56361-59e3-43f6-abb5-7c407ca48b6c.png)

Both projects don`t show the correct actual balance in the wallet. Instead of the correct balance, I see 0 INT, and ZTG tokens in my wallet.

Thank you for fixing these issues in advance.
Best regards.

**Comment by freehere107** [comment]
@ImdioR hi, sub id is not a subscan service, you can contact the sub id team

**Comment by ImdioR** [comment]
Good day Freehere107
Yes, sorry. This is my mistake.
