### ISSUE TITLE
type registry for the substrate v4.0 chain

### ISSUE THREAD

**Issue by andropixels** [subscan-explorer/subscan-essentials#200]
does substrate v4.0 chain which is a relay node  as well needs to have a type registry ?
if yes can you guide on  how to generate type registry for this kind of substrate chain ? 
and if not can i request a subscan-essentials version compatible with substrate v4.0 + relay chain ? 
Thanks in advance

**Comment by freehere107** [comment]
@andropixels substrate v4.0 no longer needs types json, The current version is available

**Comment by andropixels** [comment]
where i can find new version ?

**Comment by andropixels** [comment]
![image](https://user-images.githubusercontent.com/69791440/183228031-03ff0e59-78e3-4dbd-9342-cd4eed818554.png)
i am getting this error with a substrate v4.0.0+ relay node

**Comment by freehere107** [comment]
@andropixels It should be a problem with the node

**Comment by andropixels** [comment]
with normal template it works fine with this  below  types

  {
      "Weight": "u64",
      "CompactAssignments": "CompactAssignmentsLatest",
      "RefCount": "u32",
      "Address": "MultiAddress",
      "LookupSource": "MultiAddress",
      "AccountInfo": "AccountInfoWithTripleRefCount"
    }

    but with relay node it does not

**Comment by freehere107** [comment]
@andropixels I update https://github.com/subscan-explorer/subscan-essentials/commit/a78ad61295276479eaa6399ed83056f41f1caafe, you can update this code and try again
