### ISSUE TITLE
Add more information about locked and vested tokens

### ISSUE THREAD

**Issue by ImdioR** [subscan-explorer/subscan-essentials#230]
Hi there!
Some suggestions about how to improve and add more information for users on Subscan.
What i and other users are missing is information about locked, vested tokens.
This information is not displayed on subscan and would be really cool if you could add this in the next future updates!

Example:
Wallet address: https://centrifuge.subscan.io/account/4d7oJCLC3wrKjzofk684J5xoCJyWi2w9KSbKZyFDcR7w88Yh
The tokens are locked in the Democracy proposal until block [3214595](https://centrifuge.subscan.io/block/3214595)

Infor on subscan - only voice Democracy without any information about unlocking date.
![image](https://github.com/subscan-explorer/subscan-essentials/assets/90972248/7d23f31f-44ac-48a0-aa7a-810b5cb89918)

On polkadot.js a little bit better, however not always clear too.
![image](https://github.com/subscan-explorer/subscan-essentials/assets/90972248/49bce7b6-20b8-4fa6-8a1f-071ef67c5b05)

Would be SUPER useful and helpful if the information about locked, vested tokens could be also displayed on subscan directly!
1. Referendum number
2. Amount locked
3. Conviction used
4. Time for unlock or block time (with link to end block?)

Thank you in advance.
All the best.

**Comment by yakio** [comment]
Hi @ImdioR 
Thank you for your report! We have developed this function and applied it to all networks with governance functions, and it will be officially released in the next version.
