### ISSUE TITLE
Era index Gap

### ISSUE THREAD

**Issue by LaplaceTransformS** [subscan-explorer/subscan-essentials#236]
There are gaps in Polkadot era index values.  For instance, Era 1206 ends with block 17389831 and Era 1207 is skipped with Era 1208 starting with block 17404073.  So, blocks 17389832 through 17404072 aren't listed as Era 1207.  Ref:https://polkadot.subscan.io/validator/1dGsgLgFez7gt5WjX2FYzNCJtaCjGG6W9dA42d9cHngDYGg?tab=era
The gap is also present where Era 1169 should be.

**Comment by freehere107** [comment]
@LaplaceTransformS Thanks for your feedback. This issue has been fixed
