### ISSUE TITLE
Miss-Calculation on "Used Fee" on "shibuya-testnet", I think it need to checkup others network.

### ISSUE THREAD

**Issue by johnnyji-dev** [subscan-explorer/subscan-essentials#240]
Please Check up below description~ thx

I tried to staking on SBY on shibuya-testnet.
And then by using polkadot-api call, I found out the "amount" of used fee on "Event" info.
When "tip" existed, "(A)Used Fee" on subscan is not same with "(B)Actual used fee".
By on my trials, "Used Fee" on subscan should be only "(C)actualFee" on "event", not be calculated by subtracting "(C)actualFee" from "(D)tip".
**Question01) Is it right?**

Trials on "shibuya-testnet")
- tx-info-link : https://shibuya.subscan.io/extrinsic/0x8237b4ad0a8a35d02f176973463342f801a3906beda8b7ba1cae7a0e011e7de7
![image](https://github.com/subscan-explorer/subscan-essentials/assets/125259310/ee6ae42d-c507-40f7-95c4-cbd23dfb6217)
- "(A)Used Fee" on subscan : 0.066,796,394,258,307,080 SBY
- (x)Balance before broadcasting tx(staking) : 81.556,147,135,051,894,113 SBY
- (y)Balance after broadcasting tx(staking) : 81.488,571,369,443,536,033 SBY
- "(B)Actual used fee" = (x) - (y) = 0.067,575,765,608,300,600 SBY
- (A) is not same (B).

Additionally, by using my api-server, I can guess that the "(C)actualFee" is similar with "(B)Actual used fee".
And "(A)Used Fee" = "(C)actualFee" - "(D)tip" = 0.066,796,394,258,307,080 SBY
"(B)Actual used fee" : 0.067,575,765,608,300,600 SBY
          "(C)actualFee" : 0.067,575,765,608,358,080 SBY (0.000,000,000,000,057,480 SBY **[Question02] Is it burned?**)
                      "(D)tip" : 0.000,779,371,350,051,000 SBY
![image](https://github.com/subscan-explorer/subscan-essentials/assets/125259310/d9c87da1-5131-4e93-890c-c213ff7eb054)
![image](https://github.com/subscan-explorer/subscan-essentials/assets/125259310/d8f2f84b-d5c1-45f9-976f-72587703c50d)

**Comment by WoeOm** [comment]
(x)Balance before broadcasting tx(staking) : 81.556,147,135,051,894,113 SBY
(y)Balance after broadcasting tx(staking) : 81.488,571,369,443,536,033 SBY
"(B)Actual used fee" = (x) - (y) = 0.067,575,765,608,300,600 SBY (?)

```
new BigNumber('81.556147135051894113 ').minus('81.488571369443536033').toString()
'0.06757576560835808'
```

-----

we will support extrinsic tip.

<img width="759" alt="image" src="https://github.com/subscan-explorer/subscan-essentials/assets/7368203/89b61be6-c5ae-4f3d-a57b-2a63e3377683">

**Comment by johnnyji-dev** [comment]
Okay~ I got it thx~
