### ISSUE TITLE
Time frame queries are not working

### ISSUE THREAD

**Issue by dudo50** [subscan-explorer/subscan-essentials#246]
Hello team Subscan,

I would like to report that the time frame queries are not working.

<img width="336" alt="img" src="https://github.com/user-attachments/assets/5ab59fe4-6788-41d7-bae2-12bd09e13f0b">

See in the image; time queries just return all transactions.

The bug is encountered in the XCM Transfers tab.

With kind regards,
Dudo

**Comment by carlhong** [comment]
It is fixed now.

**Comment by dudo50** [comment]
Thanks @carlhong !

**Comment by dudo50** [comment]
Confirmed, working now! Closing issue.
